### ISSUE TITLE
Array out of bounds error

### ISSUE THREAD

**Issue by gavinheale** [SINTEF-9012/kafka-mqtt-source-connector#11]
This code seems to depend on a very specific message format and cant seem to find documentation on it.  

ERROR MqttSourceConnectorTask ERROR: Not able to create source record from mqtt message '{
  "msg": "test event 6"
}' arrived on topic 'dev-events' for client 'kafka_source_connector'.
ERROR MqttSourceConnectorTask java.lang.ArrayIndexOutOfBoundsException: Index 21 out of bounds for length 1
 java.lang.ArrayIndexOutOfBoundsException: Index 21 out of bounds for length 1
	at java.base/java.util.Arrays$ArrayList.get(Arrays.java:4351)
	at com.sintef.asam.MqttSourceConnectorTask.makeDBDoc(MqttSourceConnectorTask.java:160)
	at com.sintef.asam.MqttSourceConnectorTask.messageArrived(MqttSourceConnectorTask.java:126)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.deliverMessage(CommsCallback.java:513)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.handleMessage(CommsCallback.java:416)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.run(CommsCallback.java:213)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by AmirMassou94** [comment]
I am getting this error too and couldnt find the answer! did u solve it?

**Comment by Mocio89** [comment]
Same Here, Any Solution? Thanks

**Comment by nishant-logistiq** [comment]
same issue for me as well
